/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import java.time.LocalDate;

import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author lukas
 */
public class VelocityDlg extends javax.swing.JDialog {

    private LocalDate datum;
    private LocalTime uhrzeit;
    private String kennzeichen;
    private int vgemessen, verlaubt;
    private int überschritten;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
    DateTimeFormatter uhrzeitfor = DateTimeFormatter.ofPattern("HH:mm");
    VelocityGUI lol = new VelocityGUI();
    /**
     * Creates new form Eingabedialog
     */
    public VelocityDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfdatum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfuhrzeit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfkennzeichen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfvgemessen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfverlaubt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Datum:");
        getContentPane().add(jLabel1);

        tfdatum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfdatum.setText("08.10.2013");
        getContentPane().add(tfdatum);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Uhrzeit:");
        getContentPane().add(jLabel2);

        tfuhrzeit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfuhrzeit.setText("07:55");
        getContentPane().add(tfuhrzeit);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Kennzeichen:");
        getContentPane().add(jLabel3);

        tfkennzeichen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfkennzeichen.setText("GU-RASER1");
        getContentPane().add(tfkennzeichen);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("V-Gemessen:");
        getContentPane().add(jLabel4);

        tfvgemessen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfvgemessen.setText("123");
        getContentPane().add(tfvgemessen);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("V-Erlaubt:");
        getContentPane().add(jLabel5);

        tfverlaubt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfverlaubt.setText("80");
        getContentPane().add(tfverlaubt);

        jButton1.setText("Übernehmen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uebernehmen(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("Abbrechen");
        jButton2.setToolTipText("");
        getContentPane().add(jButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uebernehmen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uebernehmen
       datum = LocalDate.parse(tfdatum.getText(), formatter);
       uhrzeit = LocalTime.parse(tfuhrzeit.getText(), uhrzeitfor);
       kennzeichen = tfkennzeichen.getText();
       vgemessen = Integer.parseInt(tfvgemessen.getText());
       verlaubt = Integer.parseInt(tfverlaubt.getText());
       // System.out.println(datum+" "+uhrzeit+" "+kennzeichen+" "+vgemessen+" "+verlaubt);
     
        dispose();
    }//GEN-LAST:event_uebernehmen

    public LocalDate getDatum() {
        return datum;
    }

    public LocalTime getUhrzeit() {
        return uhrzeit;
    }

    public String getKennzeichen() {
        return kennzeichen;
    }

    public int getVgemessen() {
        return vgemessen;
    }

    public int getVerlaubt() {
        return verlaubt;
    }

    public int getÜberschritten() {
      
        int erg = vgemessen-verlaubt;
        return (erg);
       
    
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VelocityDlg dialog = new VelocityDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfdatum;
    private javax.swing.JTextField tfkennzeichen;
    private javax.swing.JTextField tfuhrzeit;
    private javax.swing.JTextField tfverlaubt;
    private javax.swing.JTextField tfvgemessen;
    // End of variables declaration//GEN-END:variables
}
