/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import bl.Measurment;
import bl.VelocityTableModel;
import bl.VelocityTableRenderer;
import java.awt.event.MouseEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileFilter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
 
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lukas
 */
public class VelocityGUI extends javax.swing.JFrame {

     VelocityTableModel model = new VelocityTableModel();
    VelocityDlg dialog;

    public VelocityGUI() {
       
        initComponents();
        tabelle.setModel(model);
       // model.initTestdaten();
         tabelle.setDefaultRenderer(Object.class, new VelocityTableRenderer());
  
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuee = new javax.swing.JPopupMenu();
        menu = new javax.swing.JMenu();
        hinzufuegen = new javax.swing.JMenuItem();
        loeschen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Durschnitt = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelle = new javax.swing.JTable();
        Menue = new javax.swing.JMenuBar();
        menue = new javax.swing.JMenu();
        laden = new javax.swing.JMenuItem();
        speichern = new javax.swing.JMenuItem();

        menuee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menueeMouseClicked(evt);
            }
        });

        menu.setText("Menü");

        hinzufuegen.setText("Hinzufügen");
        hinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinzufuegenActionPerformed(evt);
            }
        });
        menu.add(hinzufuegen);

        loeschen.setText("Löschen");
        loeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loeschenActionPerformed(evt);
            }
        });
        menu.add(loeschen);
        menu.add(jSeparator1);

        Durschnitt.setText("Durchschnitt");
        Durschnitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurschnittActionPerformed(evt);
            }
        });
        menu.add(Durschnitt);

        menuee.add(menu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Messungen"));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabelle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelle);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1);

        menue.setText("Datei");

        laden.setText("Laden");
        laden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladenActionPerformed(evt);
            }
        });
        menue.add(laden);

        speichern.setText("Speichern");
        speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speichernActionPerformed(evt);
            }
        });
        menue.add(speichern);

        Menue.add(menue);

        setJMenuBar(Menue);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinzufuegenActionPerformed
         dialog = new VelocityDlg(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        
        Measurment add = new Measurment(dialog.getDatum(),
        dialog.getUhrzeit(), dialog.getKennzeichen(), 
        dialog.getVgemessen(), dialog.getVerlaubt(), dialog.getÜberschritten());
        model.addElement(add);
        tabelle.repaint();
         
        
    }//GEN-LAST:event_hinzufuegenActionPerformed

    private void menueeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueeMouseClicked


    }//GEN-LAST:event_menueeMouseClicked

    private void tabelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelleMouseClicked

    }//GEN-LAST:event_tabelleMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            this.menuee.show(this, evt.getX(), evt.getY());
        }

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void loeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loeschenActionPerformed
         int selected = tabelle.getSelectedRow();
         model.delete(selected);

    }//GEN-LAST:event_loeschenActionPerformed

    private void DurschnittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurschnittActionPerformed
        int rows = tabelle.getRowCount();
        double durchschnitt = 0;
        
        int b = Integer.parseInt(tabelle.getValueAt(0, 0).toString());
        System.out.println(String.format("%f", b));
       
//        for(int i = 0; i<rows;i++)
//        {
//            System.out.println(Integer.parseInt(tabelle.getValueAt(i, 5).toString()));
//          //  durchschnitt += Integer.parseInt(tabelle.getValueAt(i, 5).toString());
//        }
//         
//        durchschnitt = durchschnitt/rows;
//       JOptionPane.showMessageDialog(this, "Die Durchschnittswert aller"
//               + "Überschreitungen beträgt: "+durchschnitt);
    }//GEN-LAST:event_DurschnittActionPerformed

    private void ladenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladenActionPerformed
        try{
            //FileNameExtensionFilter filter = new FileNameExtensionFilter("txt"); 
            JFileChooser chooser = new JFileChooser("src/Ressourcen");
//             chooser.addChoosableFileFilter(filter);
            int answer = chooser.showSaveDialog(this);
            if (answer == JFileChooser.APPROVE_OPTION) {
                File f = new File("src/Ressourcen/geschw.bin");
                 
                System.out.println("Geschwindigkeitsmessungen:"+model.toString());
                model.load(f);
                tabelle.updateUI();
            }
            }catch(Exception ex)
            {
                System.err.println("*******Main:"+ex.getMessage());
                ex.printStackTrace();
            }
    }//GEN-LAST:event_ladenActionPerformed

    private void speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speichernActionPerformed
     try{
          //FileNameExtensionFilter filter = new FileNameExtensionFilter("txt"); 
            JFileChooser chooser = new JFileChooser("src/Ressourcen");
//             chooser.addChoosableFileFilter(filter);
            int answer = chooser.showOpenDialog(this);
            if (answer == JFileChooser.APPROVE_OPTION) {
                File f = new File("src/Ressourcen/geschw.bin");
                 
                System.out.println("Geschwindigkeitsmessungen: "+model.toString());
                model.save(f);
            }
            }catch(Exception ex)
            {
                System.err.println("*******Main:"+ex.getMessage());
                ex.printStackTrace();
            }
    }//GEN-LAST:event_speichernActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VelocityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Durschnitt;
    private javax.swing.JMenuBar Menue;
    private javax.swing.JMenuItem hinzufuegen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem laden;
    private javax.swing.JMenuItem loeschen;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu menue;
    private javax.swing.JPopupMenu menuee;
    private javax.swing.JMenuItem speichern;
    private javax.swing.JTable tabelle;
    // End of variables declaration//GEN-END:variables
}
